services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build: client
    ports:
      - "5173:5173"
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data